language: cpp
    
os:
    - linux

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential qtbase5-dev qt5-qmake qt5-default boost boost-system

script:
    - qmake PokeFinder.pro
    - make
