language: cpp
rvm:
    - gcc
    
os:
    - linux
    - osx

addons:
    apt:
        packages:
            - build-essential
            - qtbase5-dev
            - qt5-qmake
            - qt5-default
            - boost
            - boost-system

script:
    - qmake PokeFinder.pro
    - make
