version: 1.0.0.{build}

os: unstable

environment:
    QTDIR: C:\Qt\5.9.1\mingw53_32
    BOOST_ROOT: C:\Libraries\boost_1_64_0
   
configuration:
    - Release

install:
    - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%
  
build_script:
    - qmake PokeFinder.pro
    - mingw32-make
    
after_build:
    -ps: |
         $GITREV = $(git show -s --format='%h')
         if (appveyor_repo_tag == true)
         {
            $BUILD_ZIP = "PokeFinder.zip"
            $BUILD_7z = "PokeFinder.7z"
         }
         else
         {
            $BUILD_ZIP = "PokeFinder-$GITREV.zip"
            $BUILD_7z = "PokeFinder-$GITREV.7z"
         }
         7z a $BUILD_ZIP .\release\PokeFinder.exe
         7z a $BUILD_ZIP C:\QT\5.9.1\mingw53_32\bin\libwinpthread-1.dll
         7z a $BUILD_ZIP C:\QT\5.9.1\mingw53_32\bin\libstdc++-6.dll
         7z a $BUILD_ZIP C:\QT\5.9.1\mingw53_32\bin\libgcc_s_dw2-1.dll
         7z a $BUILD_ZIP C:\QT\5.9.1\mingw53_32\bin\Qt5Core.dll
         7z a $BUILD_ZIP C:\QT\5.9.1\mingw53_32\bin\Qt5Gui.dll
         7z a $BUILD_ZIP C:\QT\5.9.1\mingw53_32\bin\Qt5Widgets.dll
         7z a $BUILD_ZIP C:\QT\5.9.1\mingw53_32\plugins\platforms\qwindows.dll
         7z rn $BUILD_ZIP qwindows.dll platforms\qwindows.dll
         7z a $BUILD_7z .\release\PokeFinder.exe
         7z a $BUILD_7z C:\QT\5.9.1\mingw53_32\bin\libwinpthread-1.dll
         7z a $BUILD_7z C:\QT\5.9.1\mingw53_32\bin\libstdc++-6.dll
         7z a $BUILD_7z C:\QT\5.9.1\mingw53_32\bin\libgcc_s_dw2-1.dll
         7z a $BUILD_7z C:\QT\5.9.1\mingw53_32\bin\Qt5Core.dll
         7z a $BUILD_7z C:\QT\5.9.1\mingw53_32\bin\Qt5Gui.dll
         7z a $BUILD_7z C:\QT\5.9.1\mingw53_32\bin\Qt5Widgets.dll
         7z a $BUILD_7z C:\QT\5.9.1\mingw53_32\plugins\platforms\qwindows.dll
         7z rn $BUILD_7z qwindows.dll platforms\qwindows.dll
  
artifacts:
    - path: PokeFinder-windows.zip
    - path: PokeFinder-windows.7z
    
deploy:
    provider: GitHub
    description: ''
    auth_token:
        secure: f1bnm7cWsq0pNja+DdwEkQLCMUxczFH5O8eWDEnfNnhbHKuotQ7YFS6jLYyqFbGe
    artifact: PokeFinder-windows.zip,PokeFinder-windows.7z
    draft: false
    prerelease: true
    on:
        branch: master
        appveyor_repo_tag: true