version: 1.0.0.{build}

environment:
    QTDIR: C:\Qt\5.4\mingw491_32
    BOOST_Path: C\Libraries\boost_1_64_0

install:
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw491_32\bin;%PATH%
  
build_script:
  - qmake PokeFinder.pro
  - mingw32-make   
  
artifacts:
  - path: PokéFinder.exe