environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    QTDIR: C:\Qt\5.11\msvc2017_64
    BUILDER: NMAKE
    ARCH: x64
    OS: windows
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    BUILDER: MAKE
    ARCH: x64
    OS: linux
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    QTDIR: C:\Qt\5.11\mingw53_32
    BUILDER: MINGW
    ARCH: x86
    OS: windows


services:
    - Docker

install:
    - git submodule update --init --recursive
    # Windows
    - cmd: set PATH=%QTDIR%\bin;%PATH%
    - cmd: if "%BUILDER%"=="MINGW" set PATH=C:\Qt\Tools\mingw530_32\bin;%PATH%
    - cmd: if "%BUILDER%"=="NMAKE" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    # Linux
    - sh: sudo service docker start
    
build_script:
    # Windows
    - cmd: qmake PokeFinder.pro
    - cmd: if "%BUILDER%"=="MINGW" mingw32-make
    - cmd: if "%BUILDER%"=="NMAKE" nmake
    # Linux
    - sh: docker run -w="/app" -v "$(pwd)":/app rabits/qt:%Qt_Version%-desktop sudo /opt/Qt/%Qt_Version_Full%/gcc_64/bin/qmake && make

after_build:
    # Windows
    - cmd: md PokeFinder-windows
    - cmd: move release\PokeFinder.exe PokeFinder-windows\PokeFinder.exe 
    - cmd: windeployqt --release --no-translations --no-angle --no-plugins --no-opengl-sw PokeFinder-windows\PokeFinder.exe
    - cmd: del PokeFinder-windows\vcredist*.exe
    - cmd: del PokeFinder-windows\vc_redist*.exe
    - cmd: xcopy /I %QTDIR%\plugins\platforms\qwindows.dll PokeFinder-windows\platforms\
    - cmd: xcopy /I %QTDIR%\plugins\styles\qwindowsvistastyle.dll Gen7TimeFinder-windows\styles\
    - cmd: 7z a PokeFinder-windows-%ARCH%.zip PokeFinder-windows\
    # Linux
    - sh: zip -r PokeFinder-linux-x64.zip PokeFinder
    
artifacts:
- path: PokeFinder-%OS%-%ARCH%.zip

deploy:
    provider: GitHub
    description: ''
    auth_token:
        secure: u3c5wUq11csZ77TpgKMImu9U+ibNiviMcEpTuQXmqp1YGSHA/+u5FhqZ3KRZBAQX
    artifact: PokeFinder-%OS%-%ARCH%.zip
    draft: false
    prerelease: true
    on:
        APPVEYOR_REPO_TAG: true