version: 1.3.2.{build}

environment:
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          QTDIR: C:\Qt\5.10\msvc2017_64
          BUILDER: NMAKE
          ARCH: x64
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          QTDIR: C:\Qt\5.10\mingw53_32
          BUILDER: MINGW
          ARCH: x86

configuration:
    - Release

install:
    - set PATH=%QTDIR%\bin;%PATH%
    - if "%BUILDER%"=="MINGW" set PATH=C:\Qt\Tools\mingw530_32\bin;%PATH%
    - if "%BUILDER%"=="NMAKE" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    - git submodule update --init --recursive
    
build_script:
    - qmake PokeFinder.pro
    - if "%BUILDER%"=="MINGW" mingw32-make
    - if "%BUILDER%"=="NMAKE" nmake

after_build:
    - md PokeFinder-windows
    - del Languages\*.ts
    - move Languages PokeFinder-windows\Languages
    - move release\PokeFinder.exe PokeFinder-windows\PokeFinder.exe 
    - windeployqt --release --no-translations --no-angle --no-plugins --no-opengl-sw PokeFinder-windows\PokeFinder.exe
    - del PokeFinder-windows\vcredist*.exe
    - del PokeFinder-windows\vc_redist*.exe
    - xcopy /I %QTDIR%\plugins\platforms\qwindows.dll PokeFinder-windows\platforms\
    - 7z a PokeFinder-windows-%ARCH%.zip PokeFinder-windows\
    - 7z a PokeFinder-windows-%ARCH%.7z PokeFinder-windows\
    
artifacts:
    - path: PokeFinder-windows-%ARCH%.zip
    - path: PokeFinder-windows-%ARCH%.7z

deploy:
    provider: GitHub
    description: ''
    auth_token:
        secure: f1bnm7cWsq0pNja+DdwEkQLCMUxczFH5O8eWDEnfNnhbHKuotQ7YFS6jLYyqFbGe
    artifact: PokeFinder-windows-%ARCH%.zip
    draft: false
    prerelease: true
    on:
        appveyor_repo_tag: true
