version: 1.0.0.{build}

os: unstable

environment:
    QTDIR: C:\Qt\5.9.1\mingw53_32
    BOOST_ROOT: C:\Libraries\boost_1_64_0
   
configuration:
    - Release

install:
    - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%
  
build_script:
    - qmake PokeFinder.pro
    - mingw32-make
    
after_build:
    - 7z a PokeFinder-windows-%APPVEYOR_REPO_COMMIT_TIMESTAMP%.zip .\release\PokeFinder.exe
    - 7z a PokeFinder-windows-%APPVEYOR_REPO_COMMIT_TIMESTAMP%.zip C:\QT\5.9.1\mingw53_32\bin\libwinpthread-1.dll
    - 7z a PokeFinder-windows-%APPVEYOR_REPO_COMMIT_TIMESTAMP%.zip C:\QT\5.9.1\mingw53_32\bin\libstdc++-6.dll
    - 7z a PokeFinder-windows-%APPVEYOR_REPO_COMMIT_TIMESTAMP%.zip C:\QT\5.9.1\mingw53_32\bin\libgcc_s_dw2-1.dll
    - 7z a PokeFinder-windows-%APPVEYOR_REPO_COMMIT_TIMESTAMP%.zip C:\QT\5.9.1\mingw53_32\bin\Qt5Core.dll
    - 7z a PokeFinder-windows-%APPVEYOR_REPO_COMMIT_TIMESTAMP%.zip C:\QT\5.9.1\mingw53_32\bin\Qt5Gui.dll
    - 7z a PokeFinder-windows-%APPVEYOR_REPO_COMMIT_TIMESTAMP%.zip C:\QT\5.9.1\mingw53_32\bin\Qt5Widgets.dll
    - 7z a PokeFinder-windows-%APPVEYOR_REPO_COMMIT_TIMESTAMP%.zip C:\QT\5.9.1\mingw53_32\plugins\platforms\qwindows.dll
    - 7z rn PokeFinder-windows-%APPVEYOR_REPO_COMMIT_TIMESTAMP%.zip qwindows.dll platforms\qwindows.dll
    - 7z a PokeFinder-windows-%APPVEYOR_REPO_COMMIT_TIMESTAMP%.7z .\release\PokeFinder.exe
    - 7z a PokeFinder-windows-%APPVEYOR_REPO_COMMIT_TIMESTAMP%.7z C:\QT\5.9.1\mingw53_32\bin\libwinpthread-1.dll
    - 7z a PokeFinder-windows-%APPVEYOR_REPO_COMMIT_TIMESTAMP%.7z C:\QT\5.9.1\mingw53_32\bin\libstdc++-6.dll
    - 7z a PokeFinder-windows-%APPVEYOR_REPO_COMMIT_TIMESTAMP%.7z C:\QT\5.9.1\mingw53_32\bin\libgcc_s_dw2-1.dll
    - 7z a PokeFinder-windows-%APPVEYOR_REPO_COMMIT_TIMESTAMP%.7z C:\QT\5.9.1\mingw53_32\bin\Qt5Core.dll
    - 7z a PokeFinder-windows-%APPVEYOR_REPO_COMMIT_TIMESTAMP%.7z C:\QT\5.9.1\mingw53_32\bin\Qt5Gui.dll
    - 7z a PokeFinder-windows-%APPVEYOR_REPO_COMMIT_TIMESTAMP%.7z C:\QT\5.9.1\mingw53_32\bin\Qt5Widgets.dll
    - 7z a PokeFinder-windows-%APPVEYOR_REPO_COMMIT_TIMESTAMP%.7z C:\QT\5.9.1\mingw53_32\plugins\platforms\qwindows.dll
    - 7z rn PokeFinder-windows-%APPVEYOR_REPO_COMMIT_TIMESTAMP%.7z qwindows.dll platforms\qwindows.dll
  
artifacts:
    - path: PokeFinder-windows-$(APPVEYOR_REPO_COMMIT_TIMESTAMP).zip
    - path: PokeFinder-windows-$(APPVEYOR_REPO_COMMIT).7z
    
deploy:
    provider: GitHub
    description: ''
    auth_token:
        secure: f1bnm7cWsq0pNja+DdwEkQLCMUxczFH5O8eWDEnfNnhbHKuotQ7YFS6jLYyqFbGe
    artifact: PokeFinder-windows-$(APPVEYOR_REPO_COMMIT_TIMESTAMP).zip,PokeFinder-windows-$(APPVEYOR_REPO_COMMIT_TIMESTAMP).7z
    draft: false
    prerelease: true
    on:
        branch: master
        appveyor_repo_tag: true