version: 1.0.0.{build}

os: unstable

environment:
    QTDIR: C:\Qt\5.4\mingw491_32
    BOOST_ROOT: C:\Libraries\boost_1_64_0
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_64_0\lib32-msvc-14.0
   

install:
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw491_32\bin;%PATH%
  
before_build:
    - cmd: cmake -G "Visual Studio 2017" -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBoost_USE_STATIC_LIBS="ON" -Durdfdom_DIR="%urdfdom_DIR%" -Durdfdom_headers_DIR="%urdfdom_headers_DIR%" -DDART_MSVC_DEFAULT_OPTIONS="%MSVC_DEFAULT_OPTIONS%" ..
  
build_script:
  - qmake PokeFinder.pro
  - mingw32-make   
  
artifacts:
  - path: PokéFinder.exe