version: 1.0.0.{build}

environment:
  QTDIR: C:\Qt\5.9.1\msvc2017_64
  BOOST_ROOT: C:\Libraries\boost_1_64_0
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    SHORT_MSVC_PLATFORM: x86

configuration:
    - Release

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

install:
    - set PATH=%QTDIR%\bin;%PATH%

build_script:
    - qmake PokeFinder.pro
    - nmake

after_build:
    - 7z a PokeFinder-windows.zip .\release\PokeFinder.exe
    - 7z a PokeFinder-windows.7z .\release\PokeFinder.exe

artifacts:
    - path: PokeFinder-windows.zip
    - path: PokeFinder-windows.7z

deploy:
    provider: GitHub
    description: ''
    auth_token:
        secure: f1bnm7cWsq0pNja+DdwEkQLCMUxczFH5O8eWDEnfNnhbHKuotQ7YFS6jLYyqFbGe
    artifact: PokeFinder-windows.zip,PokeFinder-windows.7z
    draft: false
    prerelease: true
    on:
        branch: master
        appveyor_repo_tag: true
