environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    QTDIR: C:\Qt\5.11\msvc2017_64
    OS: windows
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    OS: linux

services:
    - Docker

install:
    # Windows
    - cmd: set PATH=%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%
    - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    # Linux
    - sh: sudo service docker start
    
build_script:
    # Windows
    - cmd: qmake PokeFinder.pro
    - cmd: jom -j %NUMBER_OF_PROCESSORS%
    # Linux
    - sh: docker run -w="/app" -v "$(pwd)":/app rabits/qt:5.12-desktop sudo /opt/Qt/5.12.0/gcc_64/bin/qmake
    - sh: docker run -w="/app" -v "$(pwd)":/app rabits/qt:5.12-desktop sudo make -j 4
    
after_build:
    # Windows
    - cmd: md PokeFinder-windows
    - cmd: move release\PokeFinder.exe PokeFinder-windows\PokeFinder.exe 
    - cmd: windeployqt --release --no-translations --no-angle --no-plugins --no-opengl-sw PokeFinder-windows\PokeFinder.exe
    - cmd: del PokeFinder-windows\vcredist*.exe
    - cmd: del PokeFinder-windows\vc_redist*.exe
    - cmd: xcopy /I %QTDIR%\plugins\platforms\qwindows.dll PokeFinder-windows\platforms\
    - cmd: xcopy /I %QTDIR%\plugins\styles\qwindowsvistastyle.dll PokeFinder-windows\styles\
    - cmd: 7z a PokeFinder-windows.zip PokeFinder-windows\
    # Linux
    - sh: zip -r PokeFinder-linux.zip PokeFinder
    
artifacts:
- path: PokeFinder-%OS%.zip

deploy:
    provider: GitHub
    auth_token:
        secure: u3c5wUq11csZ77TpgKMImu9U+ibNiviMcEpTuQXmqp1YGSHA/+u5FhqZ3KRZBAQX
    artifact: PokeFinder-%OS%-%ARCH%.zip
    on:
        APPVEYOR_REPO_TAG: true